package com.kafshar.musicfinder

/** Additional active/reference music and lyrics sites discovered for Google site targeting. */
object MusicSiteAdditions {
    val domains: List<String> = listOf(
        "nicmusic.net",
        "vmusic.ir",
        "sakhamusic.ir",
        "jenabmusic.com",
        "ganja2music.com",
        "silamusic.ir",
        "pop-music.ir",
        "behmusic.com",
        "songsara.net",
        "farsiplayer.com",
        "sorud.com",
        "matnmusic.com",
        "dtaraneh.net",
        "trackmelody.com",
        "biya2ahang.ir",
        "songsun.ir",
        "rozsong.com",
        "sultanmusics.com",
        "musicaz.ir",
        "myspotify.ir",
        "musickordi.com",
        "shomal-music.info",
        "7gahmusic.ir",
        "ahangtv.com",
        "peraoke.com",
        "genius.com",
        "musixmatch.com",
        "lyrics.com",
        "azlyrics.com",
        "lyricfind.com",
        "songlyrics.com",
        "lyricsmode.com",
        "metrolyrics.com",
        "songmeanings.com",
        "allmusic.com",
        "musicbrainz.org",
        "discogs.com",
        "rateyourmusic.com",
        "soundcloud.com",
        "bandcamp.com",
        "audiomack.com",
        "audius.co",
        "mixcloud.com",
        "hearthis.at",
        "archive.org",
        "jamendo.com"
    ).distinct()
}
